spring.application.name=${APPLICATION_NAME}
server.port=${SERVER_PORT}

# NEON POSTGRESQL DATABASE CONFIG

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# JWT CONFIGURATION
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}